# Generated by Django 4.0.6 on 2024-05-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_autor_retrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='excerto',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
